title: Hands On DevOps
name: Carlos Castro, Wilton Silva, Rafael Moreira
theme: jekyll-theme-hacker
owner:
  github: crwlabs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: CommonMarkGhPages